language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

branches:
  only:
    - master

matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm

before_script:
  - composer self-update
  - composer install

script: phpunit
