language: php

php:
  - 7.0
  - 7.1
  - hhvm

sudo: false

branches:
  only:
    - master

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - composer self-update
  - composer install

script: if [ "$TRAVIS_PHP_VERSION" != "7.0" ] && [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then phpunit --coverage-clover=coverage.clover; else phpunit; fi

after_script:
  - if [ -e coverage.clover ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [ -e coverage.clover ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
